[project]
name = "youtube-transcript-summarizer-flask"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flasgger>=0.9.7.1",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
    "youtube-transcript-api>=1.2.3",
]
