[package]
name = "ytb"
version = "0.0.1"
description = "YouTube - Frontend"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.5.2" }

[dependencies]
serde_json = "=1.0.145"
serde = { version = "=1.0.228", features = ["derive"] }
log = "=0.4.28"
tauri = { version = "=2.9.3" }
tauri-plugin-log = "=2.7.1"
