[project]
name = "youtube-transcript-summarizer-fastapi"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.122.0",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
    "youtube-transcript-api>=1.2.3",
]
