[project]
name = "youtube-transcript-cli"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyfiglet>=1.0.4",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "yaspin>=3.3.0",
    "youtube-transcript-api>=1.2.3",
]
